env:
  es2021: true
  node: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  'no-console': 'off',
  'import/extensions': [
        'error',
        {
          js: 'always',
        },
  ],
  'no-underscore-dangle': [
        'error',
        {
          allow: ['__filename', '__dirname'],
        },
  ],
  'no-undef': 'off'
}
